### ISSUE TITLE
install git+https://bitbucket.org/silverline/spm breaks

### ISSUE THREAD

**Issue by ardavanmet** [dnakov/spm#1]
npm ERR! Command failed: Cloning into bare repository '/home/rof/.npm/_git-remotes/https-bitbucket-org-silverline-sf-junit-reporter-git-f7101cd6'...
npm ERR! remote: Invalid username or password. If you log in via a third party service you must ensure you have an account password set in your account profile.
npm ERR! fatal: Authentication failed for 'https://bitbucket.org/silverline/sf-junit-reporter.git/'

**Comment by dnakov** [comment]
Ardi!
Try now

**Comment by ardavanmet** [comment]
Amazing!
Big Boss!
